version: '3.8'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx_load_balancer
    ports:
      - "9999:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
    networks:
      - app-network

  rinha-api-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rinha-api-1
    environment:
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
      - postgres
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app

  rinha-api-2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rinha-api-2
    environment:
      - APP_PORT=${APP_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
      - POSTGRES_URL=${POSTGRES_URL}
      - NATS_URL=${NATS_URL}
    depends_on:
      - redis
      - postgres
    networks:
      - app-network
    volumes:
      - ./:/app

  redis:
    image: redis:7.2.4-alpine
    container_name: redis_cache
    networks:
      - app-network

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nats:
    image: nats:2.10.14-alpine
    container_name: nats_server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin_gui
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
