version: '3.8'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx_load_balancer
    ports:
      - "9999:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
    networks:
      - app-network

  rinha-api-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rinha-api-1
    environment:
      - APP_PORT=3000
      - REDIS_ADDR=redis:6379
      - POSTGRES_URL=postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
      - NATS_URL=nats://nats:4222
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app

  rinha-api-2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rinha-api-2
    environment:
      - APP_PORT=${APP_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
      - POSTGRES_URL=${POSTGRES_URL}
      - NATS_URL=${NATS_URL}
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network
      - payment-processor
    volumes:
      - ./:/app

  redis:
    image: redis:7.2.4-alpine
    container_name: redis_cache
    networks:
      - app-network

  nats:
    image: nats:2.10.14-alpine
    container_name: nats_server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - app-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very_hard_password
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "5051:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very_hard_password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
  mongo_data:
